home:
    pattern:  /
    defaults: { _controller: DornCMS:PageController:view, template: pages/home.html }
    requirements:
        _method: GET
contact:
    pattern:  /contact
    defaults: { _controller: DornCMS:PageController:view, template: pages/contact.html }
    requirements:
        _method: GET

contact_submit:
    pattern:  /contact
    defaults: { _controller: FrontEnd:ContactController:submit }
    requirements:
        _method: POST
