home:
    pattern:  /
    defaults: { _controller: DornCMS:PageController:view, template: pages/home.html }
    requirements:
        _method: GET

edit:
    pattern:  /edit
    defaults: { _controller: DornCMS:PageController:edit, template: pages/home.html }
    requirements:
        _method: GET

edit_element:
    pattern:  /edit_element
    defaults: { _controller: DornCMS:PageController:edit, template: elements/home/title.html }
    requirements:
        _method: GET
