home:
    pattern:  /
    defaults: { _controller: DornCMS:PageController:home, template: pages/home.html }
    requirements:
        _method: GET

edit:
    pattern:  /edit
    defaults: { _controller: DornCMS:PageController:edit, template: pages/home.html }
    requirements:
        _method: GET
